#!/bin/zsh
#
# ╔═══════════════════════════════════════════════════════════════════════════╗
# ║                        FPL REPORT GENERATOR                               ║
# ╠═══════════════════════════════════════════════════════════════════════════╣
# ║  Generates comprehensive Fantasy Premier League analysis reports          ║
# ║                                                                           ║
# ║  This script:                                                             ║
# ║    1. Fetches live data from the official FPL API                         ║
# ║    2. Analyzes your squad (form trends, ICT, xG/xA, peer comparisons)     ║
# ║    3. Identifies underperforming players with transfer suggestions        ║
# ║    4. Generates a professional LaTeX report                               ║
# ║    5. Compiles to PDF                                                     ║
# ║                                                                           ║
# ║  The script automatically detects the current gameweek from the FPL API.  ║
# ║  You can override this by specifying a gameweek number.                   ║
# ╚═══════════════════════════════════════════════════════════════════════════╝
#
# USAGE:
#   ./run_report.sh [OPTIONS] [TEAM_ID] [GAMEWEEK]
#
# ARGUMENTS:
#   TEAM_ID     Your FPL team ID (find it in your team URL on the FPL website)
#               Example: https://fantasy.premierleague.com/entry/847569/event/1
#                                                              ^^^^^^
#               Default: 847569
#
#   GAMEWEEK    Specific gameweek to analyze (1-38)
#               Default: Current gameweek (auto-detected from FPL API)
#
# OPTIONS:
#   -h, --help      Show this help message and exit
#   -q, --quiet     Suppress Python script output (show only status messages)
#   -k, --keep      Keep auxiliary files (.aux, .log, .out) after compilation
#   -n, --no-open   Don't prompt to open PDF after generation (macOS only)
#
# EXAMPLES:
#   ./run_report.sh                     # Generate report for default team, current GW
#   ./run_report.sh 847569              # Generate report for team 847569, current GW
#   ./run_report.sh 847569 16           # Generate report for team 847569, GW16
#   ./run_report.sh -q 847569           # Quiet mode - less output
#   ./run_report.sh --help              # Show this help message
#
# OUTPUT FILES:
#   report_<TEAM_ID>.tex    LaTeX source file
#   report_<TEAM_ID>.pdf    Final PDF report (7+ pages)
#
# REQUIREMENTS:
#   - Python 3 with packages: pandas, numpy, scipy, requests
#   - pdflatex (TeX Live or MacTeX)
#   - Internet connection (to fetch FPL API data)
#
# FINDING YOUR TEAM ID:
#   1. Log in to https://fantasy.premierleague.com
#   2. Click "Points" to view your team
#   3. Look at the URL: https://fantasy.premierleague.com/entry/XXXXXX/event/1
#   4. The number after /entry/ is your Team ID
#
# REPORT CONTENTS:
#   - Title page with season stats
#   - Gameweek performance charts (points & rank progression)
#   - Current squad formation diagram
#   - Player deep dive analysis (form, ICT, xG/xA, peer comparison)
#   - Transfer recommendations with replacement suggestions
#   - Chip usage strategy
#   - Season insights and projected finish
#
# AUTHOR: Generated by Claude Code
# ═══════════════════════════════════════════════════════════════════════════════

set -e  # Exit on error

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$SCRIPT_DIR/config.yml"
PYTHON_SCRIPT="$SCRIPT_DIR/generate_fpl_report.py"

# Read settings from config.yml (same directory as this script)
if [[ -f "$CONFIG_FILE" ]]; then
    # Parse YAML with grep/sed (portable, no yq dependency)
    DEFAULT_TEAM_ID=$(grep -E '^team_id:' "$CONFIG_FILE" 2>/dev/null | sed 's/^team_id:[[:space:]]*//' | tr -d ' ')
    DEFAULT_GAMEWEEK=$(grep -E '^gameweek:' "$CONFIG_FILE" 2>/dev/null | sed 's/^gameweek:[[:space:]]*//' | tr -d ' ')
    
    # Handle null/empty values
    [[ -z "$DEFAULT_TEAM_ID" || "$DEFAULT_TEAM_ID" == "null" ]] && DEFAULT_TEAM_ID=847569
    [[ "$DEFAULT_GAMEWEEK" == "null" || "$DEFAULT_GAMEWEEK" == "~" ]] && DEFAULT_GAMEWEEK=""
else
    echo "[WARNING] Config file not found: $CONFIG_FILE"
    echo "         Create reports/config.yml to configure your settings."
    DEFAULT_TEAM_ID=847569
    DEFAULT_GAMEWEEK=""
fi

# Auto-detect Python environment
if [[ -f "$PROJECT_ROOT/venv/bin/python" ]]; then
    PYTHON_CMD="$PROJECT_ROOT/venv/bin/python"
elif [[ -f "$PROJECT_ROOT/.venv/bin/python" ]]; then
    PYTHON_CMD="$PROJECT_ROOT/.venv/bin/python"
else
    PYTHON_CMD="python3"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Colors for terminal output
# ─────────────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ─────────────────────────────────────────────────────────────────────────────
# Help function
# ─────────────────────────────────────────────────────────────────────────────
show_help() {
    cat << 'EOF'
╔═══════════════════════════════════════════════════════════════════════════╗
║                        FPL REPORT GENERATOR                               ║
╠═══════════════════════════════════════════════════════════════════════════╣
║  Generates comprehensive Fantasy Premier League analysis reports          ║
║                                                                           ║
║  This script:                                                             ║
║    1. Fetches live data from the official FPL API                         ║
║    2. Analyzes your squad (form trends, ICT, xG/xA, peer comparisons)     ║
║    3. Identifies underperforming players with transfer suggestions        ║
║    4. Generates a professional LaTeX report                               ║
║    5. Compiles to PDF                                                     ║
║                                                                           ║
║  The script automatically detects the current gameweek from the FPL API.  ║
║  You can override this by specifying a gameweek number.                   ║
╚═══════════════════════════════════════════════════════════════════════════╝

USAGE:
  ./run_report.sh [OPTIONS] [TEAM_ID] [GAMEWEEK]

ARGUMENTS:
  TEAM_ID     Your FPL team ID (find it in your team URL on the FPL website)
              Example: https://fantasy.premierleague.com/entry/847569/event/1
                                                             ^^^^^^
              Default: 847569

  GAMEWEEK    Specific gameweek to analyze (1-38)
              Default: Current gameweek (auto-detected from FPL API)

OPTIONS:
  -h, --help      Show this help message and exit
  -q, --quiet     Suppress Python script output (show only status messages)
  -k, --keep      Keep auxiliary files (.aux, .log, .out) after compilation
  -n, --no-open   Don't prompt to open PDF after generation (macOS only)

EXAMPLES:
  ./run_report.sh                     # Generate for default team, current GW
  ./run_report.sh 847569              # Generate for team 847569, current GW
  ./run_report.sh 847569 16           # Generate for team 847569, GW16
  ./run_report.sh -q 847569           # Quiet mode - less output
  ./run_report.sh --help              # Show this help message

OUTPUT FILES:
  report_<TEAM_ID>.tex    LaTeX source file
  report_<TEAM_ID>.pdf    Final PDF report (7+ pages)

REQUIREMENTS:
  - Python 3 with packages: pandas, numpy, scipy, requests
  - pdflatex (TeX Live or MacTeX)
  - Internet connection (to fetch FPL API data)

FINDING YOUR TEAM ID:
  1. Log in to https://fantasy.premierleague.com
  2. Click "Points" to view your team
  3. Look at the URL: https://fantasy.premierleague.com/entry/XXXXXX/event/1
  4. The number after /entry/ is your Team ID

REPORT CONTENTS:
  - Title page with season stats
  - Gameweek performance charts (points & rank progression)
  - Current squad formation diagram
  - Player deep dive analysis (form, ICT, xG/xA, peer comparison)
  - Transfer recommendations with replacement suggestions
  - Chip usage strategy
  - Season insights and projected finish
EOF
    exit 0
}

# ─────────────────────────────────────────────────────────────────────────────
# Parse command line arguments
# ─────────────────────────────────────────────────────────────────────────────
QUIET_MODE=0
KEEP_AUX=0
NO_OPEN=0
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            show_help
            ;;
        -q|--quiet)
            QUIET_MODE=1
            shift
            ;;
        -k|--keep)
            KEEP_AUX=1
            shift
            ;;
        -n|--no-open)
            NO_OPEN=1
            shift
            ;;
        -*)
            echo "${RED}[ERROR]${NC} Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
        *)
            POSITIONAL_ARGS+=("$1")
            shift
            ;;
    esac
done

# Restore positional arguments
set -- "${POSITIONAL_ARGS[@]}"

# Use config values, allow positional overrides (deprecated - use config.yml)
TEAM_ID="${1:-$DEFAULT_TEAM_ID}"
GAMEWEEK="${2:-$DEFAULT_GAMEWEEK}"

# Fallback to auto-detect if no gameweek specified
if [[ -z "$GAMEWEEK" ]]; then
    echo "${CYAN}[INFO] Gameweek: auto-detect (set in config.yml to override)${NC}"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Validate inputs
# ─────────────────────────────────────────────────────────────────────────────
if ! [[ "$TEAM_ID" =~ ^[0-9]+$ ]]; then
    echo "${RED}[ERROR]${NC} Invalid team ID: $TEAM_ID (must be a number)"
    echo "Use --help for usage information"
    exit 1
fi

if [[ -n "$GAMEWEEK" ]] && ! [[ "$GAMEWEEK" =~ ^[0-9]+$ ]]; then
    echo "${RED}[ERROR]${NC} Invalid gameweek: $GAMEWEEK (must be a number 1-38)"
    exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Check dependencies
# ─────────────────────────────────────────────────────────────────────────────
check_dependency() {
    if ! command -v "$1" &> /dev/null; then
        echo "${RED}[ERROR]${NC} Required command not found: $1"
        echo "Please install $2"
        exit 1
    fi
}

check_dependency "$PYTHON_CMD" "Python 3"
check_dependency "pdflatex" "TeX Live (brew install --cask mactex-no-gui) or MacTeX"

# ─────────────────────────────────────────────────────────────────────────────
# Main script
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "${BLUE}  ${BOLD}FPL Report Generator${NC}"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  ${CYAN}Team ID:${NC}  $TEAM_ID"
if [[ -n "$GAMEWEEK" ]]; then
    echo "  ${CYAN}Gameweek:${NC} $GAMEWEEK (specified)"
else
    echo "  ${CYAN}Gameweek:${NC} Auto-detect (current)"
fi
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Step 1: Run Python data fetcher
# ─────────────────────────────────────────────────────────────────────────────
echo "${YELLOW}[1/3]${NC} Fetching data and generating LaTeX..."

# Build Python arguments as array for proper handling
PYTHON_ARGS=("--team" "$TEAM_ID" "--no-pdf")
if [[ -n "$GAMEWEEK" ]]; then
    PYTHON_ARGS+=("--gw" "$GAMEWEEK")
fi

PYTHON_EXIT=0
if [[ $QUIET_MODE -eq 1 ]]; then
    "$PYTHON_CMD" "$PYTHON_SCRIPT" "${PYTHON_ARGS[@]}" > /dev/null 2>&1 || PYTHON_EXIT=$?
else
    "$PYTHON_CMD" "$PYTHON_SCRIPT" "${PYTHON_ARGS[@]}" || PYTHON_EXIT=$?
fi

if [[ $PYTHON_EXIT -ne 0 ]]; then
    echo "${RED}[ERROR]${NC} Python script failed! (exit code: $PYTHON_EXIT)"
    echo "Try running with verbose output: python3 $PYTHON_SCRIPT $PYTHON_ARGS -v"
    exit 1
fi

# Define output files
TEX_FILE="$SCRIPT_DIR/report_${TEAM_ID}.tex"
PDF_FILE="$SCRIPT_DIR/report_${TEAM_ID}.pdf"
LOG_FILE="$SCRIPT_DIR/report_${TEAM_ID}.log"
AUX_FILE="$SCRIPT_DIR/report_${TEAM_ID}.aux"
OUT_FILE="$SCRIPT_DIR/report_${TEAM_ID}.out"

# Verify LaTeX file was created
if [[ ! -f "$TEX_FILE" ]]; then
    echo "${RED}[ERROR]${NC} LaTeX file not found: $TEX_FILE"
    exit 1
fi

echo "${GREEN}[OK]${NC} LaTeX file generated"

# ─────────────────────────────────────────────────────────────────────────────
# Step 2: Compile LaTeX to PDF
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "${YELLOW}[2/3]${NC} Compiling PDF (first pass)..."
cd "$SCRIPT_DIR"

# First pass (warnings are expected, ignore exit code)
pdflatex -interaction=nonstopmode "report_${TEAM_ID}.tex" > /dev/null 2>&1 || true

# Second pass for cross-references (hyperlinks, TOC, etc.)
echo "${YELLOW}[2/3]${NC} Compiling PDF (second pass)..."
pdflatex -interaction=nonstopmode "report_${TEAM_ID}.tex" > /dev/null 2>&1 || true

# Check if PDF was created and has content (success criteria)
COMPILE_ERROR=0
if [[ -f "$PDF_FILE" ]]; then
    PDF_SIZE_BYTES=$(stat -f%z "$PDF_FILE" 2>/dev/null || stat -c%s "$PDF_FILE" 2>/dev/null || echo "0")
    if [[ "$PDF_SIZE_BYTES" -gt 10000 ]]; then
        PDF_SIZE=$(ls -lh "$PDF_FILE" | awk '{print $5}')
        PDF_PAGES=$(pdfinfo "$PDF_FILE" 2>/dev/null | grep "Pages:" | awk '{print $2}' || echo "?")
        echo "${GREEN}[OK]${NC} PDF generated: report_${TEAM_ID}.pdf ($PDF_PAGES pages, $PDF_SIZE)"
    else
        echo "${RED}[ERROR]${NC} PDF generated but appears corrupt (too small)"
        COMPILE_ERROR=1
    fi
else
    echo "${RED}[ERROR]${NC} PDF compilation failed!"
    echo "${YELLOW}[INFO]${NC} Check log file: $LOG_FILE"
    COMPILE_ERROR=1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Step 3: Clean up auxiliary files (only if no errors and not --keep)
# ─────────────────────────────────────────────────────────────────────────────
echo ""
if [[ $COMPILE_ERROR -eq 0 ]] && [[ $KEEP_AUX -eq 0 ]]; then
    echo "${YELLOW}[3/3]${NC} Cleaning up auxiliary files..."
    rm -f "$AUX_FILE" "$LOG_FILE" "$OUT_FILE" 2>/dev/null
    echo "${GREEN}[OK]${NC} Cleanup complete"
elif [[ $KEEP_AUX -eq 1 ]]; then
    echo "${YELLOW}[3/3]${NC} Keeping auxiliary files (--keep specified)"
else
    echo "${YELLOW}[3/3]${NC} Skipping cleanup (errors detected)"
    echo "${YELLOW}[INFO]${NC} Log file preserved: $LOG_FILE"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [[ $COMPILE_ERROR -eq 0 ]]; then
    echo "${GREEN}  ✓ Report generated successfully!${NC}"
    echo ""
    echo "  ${CYAN}Output:${NC} $PDF_FILE"
else
    echo "${YELLOW}  ⚠ Report generated with warnings${NC}"
    echo ""
    echo "  ${CYAN}Output:${NC} $PDF_FILE"
    echo "  ${CYAN}Log:${NC}    $LOG_FILE"
fi
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────────────────
# Open PDF (macOS only, interactive mode only)
# ─────────────────────────────────────────────────────────────────────────────
if [[ "$(uname)" == "Darwin" ]] && [[ -f "$PDF_FILE" ]] && [[ $NO_OPEN -eq 0 ]] && [[ -t 0 ]]; then
    read -q "REPLY?Open PDF in Preview? [y/N] "
    echo ""
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        open "$PDF_FILE"
    fi
fi

exit $COMPILE_ERROR
